name 'mysql_wrapper'
maintainer       'binoy'
maintainer_email 'binoy@gmail.com'
license          'all_rights'
description      'mysql'
long_description 'mysql'
version          '0.1.0'
depends 'mysql', '~> 8.0'
